// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintlyServer.Data;

#nullable disable

namespace PrintlyServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260122000000_AddRoleToUser")]
    partial class AddRoleToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            // This is a partial migration - the full model is defined in DatabaseContextModelSnapshot
            // This file only shows the changes made in this migration
        }
    }
}
